### ISSUE TITLE
Minor incompatibility with ChannelTabs

### ISSUE THREAD

**Issue by fowlis** [DiscordStyles/Fluent#78]
### Describe the bug
The button to add a new tab is unclickable with Fluent enabled

### To Reproduce
1. Download these
	1a. [Fluent](https://betterdiscord.app/theme/Fluent) ([direct download](https://betterdiscord.app/Download?id=662))
	1b. [ChannelTabs](https://betterdiscord.app/plugin/ChannelTabs) ([direct download](https://betterdiscord.app/Download?id=195))
2. Enable them together
### Screenshots
![](https://cdn.upload.systems/uploads/uxuO47Kb.gif)

### Infomation (please complete the following information)
**Discord channel**: *PTB*  
**OS**: *Windows*  
**Mod**: *BetterDiscord*  
**Discord language**: English (UK)  

### Additional context
The other buttons work fine, the < and > and quick settings button all function properly

**Comment by Gibbu** [comment]
The previous and next buttons work because the titlebar does not stretch the full 100%.
This is so I can get the Close Settings button to work.

**Comment by itoffie** [comment]
```css
.winButton-3UMjdg{
  height: calc(var(--win-btn-height)+ 4px);
  width: 40px;
}

.typeWindows-2-g3UY {
  height: var(--win-btn-height);
  z-index: 2;
  background: transparent;
  position: fixed;
  max-width: calc(100% - 90% - var(--server-size));
  -webkit-user-select: none;
     -moz-user-select: none;
          user-select: none;
  pointer-events: none;
  right: 1%;
}

.platform-win #app-mount .typeWindows-2-g3UY + div .layer-86YKbF.baseLayer-W6S8cY {
    padding-top: calc(var(--win-btn-height) + -5%) !important;
    padding-bottom: -5;
}

#channelTabs-container{
  max-width: 91%;
}
```

temp custom css that i basically customized so things becomes clickable @fowlis
