### ISSUE TITLE
User profile modal incorrect layout.

### ISSUE THREAD

**Issue by trungnt2910** [DiscordStyles/Fluent#84]
### Describe the bug
*A clear and concise description of what the bug is*  

### To Reproduce  
*Steps to reproduce the behavior*  
- Install this theme.
- Enter any random server.
- Click on any random user on the left bar.
- Click on their profile picture again to open the user profile modal.

### Screenshots
*If applicable, add screenshots to help explain your problem*

![image](https://user-images.githubusercontent.com/57174311/192515508-7bf4dfa1-6db7-403d-a7d2-f875d6dfddcd.png)

### Infomation (please complete the following information)
**Discord channel**: *Stable*  
**OS**: *Windows*  
**Mod**: *BetterDiscord*  
**Discord language**: *English*  

### Additional context
*Add any other context about the problem here. Remove if not applicable.*  
To fix the issue:

```css
#app-mount .topSection-13QKHs .bannerSVGWrapper-qc0szY {
  position: absolute;
  top: 0;
  left: 0;
  -webkit-mask: linear-gradient(hsla(0deg, 0%, 0%, 0.5), transparent 80%);
  mask: linear-gradient(hsla(0deg, 0%, 0%, 0.5), transparent 80%);
}
#app-mount .topSection-13QKHs .bannerSVGWrapper-qc0szY circle {
  display: none;
}
```

Normal user:
![image](https://user-images.githubusercontent.com/57174311/192518933-837c63ae-390a-4ea9-809d-fa5d73cc476d.png)

User with Nitro:
![image](https://user-images.githubusercontent.com/57174311/192518795-89e58c2e-5f10-4c20-9f76-fa41ef626e92.png)
