### ISSUE TITLE
Members sidebar shifted when using ServerFolders

### ISSUE THREAD

**Issue by maicol07** [DiscordStyles/Fluent#93]
### Describe the bug
When [ServerFolders](https://betterdiscord.app/plugin/ServerFolders) and you open a folder in a new column, the right sidebar shifts over the window edge. This behaviour is not present in the default Discord theme.

### To Reproduce
1. Install Fluent and [ServerFolders](https://betterdiscord.app/plugin/ServerFolders)
2. Ensure the "Move the servers from opened folder in an extra column" setting is enabled in ServerFolders settings.
3. Make a server folder and see bug

### Screenshots

|               | Fluent | Discord Default |
|---------------|--------|-----------------|
| Folder closed | ![image](https://github.com/DiscordStyles/Fluent/assets/9463142/d410281a-6ab9-4b91-a1ef-b9eaa97ff46b) | ![image](https://github.com/DiscordStyles/Fluent/assets/9463142/e9729d09-6d0f-46fd-9c52-07392fe95c8b) |
| Folder opened | ![image](https://github.com/DiscordStyles/Fluent/assets/9463142/e3cf150a-bc67-480e-84bf-374374851ca9) | ![image](https://github.com/DiscordStyles/Fluent/assets/9463142/3e0e4c02-6f2e-424f-ab45-59f472e5042d) |

### Infomation (please complete the following information)

**Discord channel**: _PTB_  
**OS**: _Windows_  
**Mod**: _BetterDiscord_  
**Discord language**: _Italian_

**Comment by maicol07** [comment]
Temporary fix:
```css
.content-Pph8t6:not(.closed-j55_T-) + .base-2jDfDU .content-1SgpWY {
    width: calc(100vw - var(--server-container) - var(--server-container));
}

.content-1SgpWY {
    transition: width 0.25s cubic-bezier(.44,1.04,1,1.01) !important;
}
```
